---
version: "3.2"
services:
  builder:
    build:
      context: 1/
    volumes:
      - type: volume
        source: site
        target: /usr/local/tomcat/target
    ports:
      - "8081:8080"

  web:
    image: tomcat:8.5.3-jre8-alpine
    volumes:
      - type: volume
        source: site
        target: /usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    depends_on:
      - builder

volumes:
  site:
...






