---
version: "3.2"
services:
  builder:
    build:
      context: 1/
    volumes:
      - site:/usr/local/tomcat/target/hello-1.0

  web:
    image: tomcat:8.5.3-jre8-alpine
    volumes:
      - site:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"

volumes:
  site:
...






